import {StyleSheet} from 'react-native';
import {Colors} from 'react-native/Libraries/NewAppScreen';
import Color from '../../constant/Color';
export const styles = StyleSheet.create({
  image: {
    flex: 1,
    resizeMode: 'cover',
    justifyContent: 'center',
  },
  demo: {
    backgroundColor: Color.cream,
    width: '90%',
    height: 500,
    borderRadius: 10,
    left: '35%',
    marginLeft: '-30%',
    alignItems: 'center',
  },
  signuppage: {
    borderColor: Color.Black,
    borderWidth: 0.1,
    height: '25%',
    backgroundColor: Color.White,
    right: '20%',
    shadowColor: Color.Black,
    shadowOffset: {width: 0, height: 1},
    shadowRadius: 2,
    shadowOpacity: 0.05,
    elevation: 2,
    width: '100%',
    left: '0.2%',
    marginTop: 0.7,
    padding: '0.5 %',
    alignItems: 'center',
  },
  button: {
    borderColor: Color.Black,
    borderWidth: 0,
    backgroundColor: Color.White,
    shadowColor: Color.Black,
    shadowOffset: {width: 0, height: 1},
    shadowRadius: 2,
    shadowOpacity: 0.05,
    elevation: 2,
    height: '100%',
    alignItems: 'center',
    padding: 0,
  },
  searchSection: {
    marginTop: '20%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '90%',
    borderColor: Color.Black,
    borderWidth: 0,
    backgroundColor: Color.White,
    shadowColor: Color.Black,
    shadowOffset: {width: 0, height: 1},
    shadowRadius: 2,
    shadowOpacity: 0.05,
    elevation: 2,
  },
  marginTop5: {marginTop: '05%'},

  ViewStyle: {
    marginTop: 5,
    borderColor: Color.Black,
    borderWidth: 0.1,
    height: '70%',
    borderTopColor: Color.White,
    backgroundColor: Color.White,
    right: '20%',
    shadowColor: Color.Black,
    shadowOffset: {width: 0, height: 1},
    shadowRadius: 2,
    shadowOpacity: 0.05,
    elevation: 4,
    borderRadius: 4,
  },
  Icon: {flexDirection: 'row', marginBottom: 10, top: 7, left: 10},
  IconButton: {color: Color.Blue, marginLeft: 10, fontSize: 18},
  marginLeft: {marginLeft: 10},
  marginLeft20: {marginLeft: 20},
  Top20: {color: Color.Blur_Black, top: 20, fontSize: 12},
  padding5: {padding: 5},
  checkbox: {flexDirection: 'row', top: '07%', marginRight: '45%'},
  check: {borderWidth: 3},
  Top3: {top: '03%'},
  buttonComponent: {width: '70%', top: '05%'},
  Textcolor: {color: Color.Blur_Black},
  ViewInput: {width: '80%', marginLeft: '5%'},
  ViewIcon: {width: 'auto', marginLeft: '5%'},
  Top30: {marginTop: 30},
});
