import {StyleSheet} from 'react-native';

import Color from '../../constant/Color';
const styles = StyleSheet.create({
  image: {
    flex: 1,
    resizeMode: 'cover',
    justifyContent: 'center',
  },
  demo: {
    width: '90%',
    height: 500,
    borderRadius: 10,
    left: '35%',
    marginLeft: '-30%',
    alignItems: 'center',
  },
  signuppage: {
    borderColor: Color.Black,
    borderWidth: 0.1,
    height: '20%',
    backgroundColor: Color.White,
    right: '20%',
    shadowColor: Color.Black,
    shadowOffset: {width: 0, height: 1},
    shadowRadius: 2,
    shadowOpacity: 0.05,
    elevation: 2,
    width: '100%',
    left: '0.2%',
    marginTop: 0.7,
    padding: '0.5%',
    alignItems: 'center',
  },
  Textcolor: {color: Color.Blur_Black},
  row: {flexDirection: 'row'},
  button: {
    borderColor: Color.Black,
    borderWidth: 0,
    backgroundColor: Color.White,
    shadowColor: Color.Black,
    shadowOffset: {width: 0, height: 1},
    shadowRadius: 2,
    shadowOpacity: 0.05,
    elevation: 2,
    height: '70%',
    alignItems: 'center',
  },
  IconText: {color: Color.Blue, marginLeft: 10, fontSize: 18},
  margin20: {marginLeft: 20},
  margin10: {marginLeft: 10},
  Textsing: {color: Color.Blur_Black, top: 20},
  searchSection: {
    marginTop: '15%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '90%',
    borderColor: Color.Black,
    borderWidth: 0,
    backgroundColor: Color.White,
    shadowColor: Color.Black,
    shadowOffset: {width: 0, height: 1},
    shadowRadius: 2,
    shadowOpacity: 0.05,
    elevation: 2,
  },
  marginTop5: {marginTop: '05%'},
  ViewIcon: {width: 'auto', marginLeft: '5%'},
  padding5: {padding: 5},
  ViewInput: {width: '80%', marginLeft: '5%'},
  checkbox: {flexDirection: 'row', top: '07%', marginRight: '27%'},
  checkBox: {borderWidth: 3},
  Top3: {top: '03%'},
  colorTop: {color: Color.Purple, top: '03%'},
  Buttocomponet: {width: '70%', top: '10%'},
});
export default styles;
